import React from "react";
import { createBrowserRouter } from "react-router-dom";
import App from "../App";
import * as Pages from "../Pages";

const {
  LandingPage,
  ErrorPage,
  NotFoundPage,
  AdmissionPage,
  ApplyForASemister,
  AddStudentClassTest_Lab,
  EditStudentClassTest_Lab,
  StudentClassTest_Lab_List,
  StudentDashboard,
  StudentEditProfile,
  StudentNotification,
  ViewClassRoutine,
  ViewStudentResult,
  StudentLogin,
  TeacherLogin,
  ClassRoutine,
  EditTeacherProfile,
  PostClassTest,
  PublishResult,
  TeacherDashboard,
  TeacherNotification,
  AdminLogin,
  AdminDashboard,
  AdminAddBatch,
  AdminAddRoutine,
  AdminAddStudent,
  AdminAddTeacher,
  AdminAddSubject,
  AdminBatchList,
  AdminClass_test_Lab_List,
  AdminEditBatch,
  AdminEditRoutine,
  AdminEditStudent,
  AdminEditSubject,
  AdminEditTeacher,
  AdminResultList,
  AdminRoutineList,
  AdminSemisterApprovalList,
  AdminStudentList,
  AdminSubjectList,
  AdmissionApprovalList,
  EditStudentResult,
  PostStudentResult,
  AdminTeacherList,
  TeacherClassTestList,
  EditClassTest,
  TeacherAddExperience,
  TeacherAddDegree,
  TeacherPublishResultList,
  StudentProfile,
} = Pages;

export const router = createBrowserRouter([
  {
    path: "/",
    element: <App />,
    errorElement: <ErrorPage />,
    children: [
      { path: "/", element: <LandingPage /> },
      { path: "/home", element: <LandingPage /> },
      {
        path: "/admission",
        element: <AdmissionPage />
      },
      // Student Routes
      { path: "/student/login", element: <StudentLogin /> },
      { path: "/student/apply-semester", element: <ApplyForASemister /> },
      { path: "/student/add-class-test-lab", element: <AddStudentClassTest_Lab /> },
      { path: "/student/edit-class-test-lab", element: <EditStudentClassTest_Lab /> },
      { path: "/student/class-test-lab-list", element: <StudentClassTest_Lab_List /> },
      { path: "/student/dashboard", element: <StudentDashboard /> },
      { path: "/student/edit-profile", element: <StudentEditProfile /> },
      { path: "/student/notifications", element: <StudentNotification /> },
      { path: "/student/class-routine", element: <ViewClassRoutine /> },
      { path: "/student/view-results", element: <ViewStudentResult /> },
      { path: "/student/profile", element: <StudentProfile /> },

      // Teacher Routes
      { path: "/teacher/login", element: <TeacherLogin /> },
      {
        path: "/teacher",
        element: <TeacherDashboard />,
        children: [
          { path: "dashboard", element: <TeacherDashboard /> },
          { path: "class-routine", element: <ClassRoutine /> },
          { path: "edit-profile", element: <EditTeacherProfile /> },
          { path: "post-class-test", element: <PostClassTest /> },
          { path: "publish-result", element: <PublishResult /> },
          { path: "notifications", element: <TeacherNotification /> },
          { path: "class-test-list", element: <TeacherClassTestList /> },
          { path: "edit-class-test/:id", element: <EditClassTest /> },
          { path: "add-experience", element: <TeacherAddExperience /> },
          { path: "add-degree", element: <TeacherAddDegree /> },
          { path: "publish-result-list", element: <TeacherPublishResultList /> },
        ],
      },

      // Admin Routes
      { path: "/admin/login", element: <AdminLogin /> },
      {
        path: "/admin",
        element: <AdminDashboard />,
        children: [
          { path: "dashboard", element: <AdminDashboard /> },
          { path: "add-batch", element: <AdminAddBatch /> },
          { path: "add-routine", element: <AdminAddRoutine /> },
          { path: "add-student", element: <AdminAddStudent /> },
          { path: "add-teacher", element: <AdminAddTeacher /> },
          { path: "add-subject", element: <AdminAddSubject /> },
          { path: "batch-list", element: <AdminBatchList /> },
          { path: "class-test-lab-list", element: <AdminClass_test_Lab_List /> },
          { path: "edit-batch/:id", element: <AdminEditBatch /> },
          { path: "edit-routine/:id", element: <AdminEditRoutine /> },
          { path: "edit-student/:id", element: <AdminEditStudent /> },
          { path: "edit-subject/:id", element: <AdminEditSubject /> },
          { path: "edit-teacher/:id", element: <AdminEditTeacher /> },
          { path: "result-list", element: <AdminResultList /> },
          { path: "routine-list", element: <AdminRoutineList /> },
          { path: "semester-approval-list", element: <AdminSemisterApprovalList /> },
          { path: "student-list", element: <AdminStudentList /> },
          { path: "teacher-list", element: <AdminTeacherList /> },
          { path: "subject-list", element: <AdminSubjectList /> },
          { path: "admission-approval-list", element: <AdmissionApprovalList /> },
          { path: "edit-student-result/:id", element: <EditStudentResult /> },
          { path: "post-student-result", element: <PostStudentResult /> },
        ],
      },

      { path: "*", element: <NotFoundPage /> },
    ],
  },
]);
