export const studentList = [
  {
    id: 1,
    name: "Arif Hossain",
    email: "arif.hossain@gmail.com",
    phone: "+8801781234567",
    dob: "1998-06-21",
    address: "Dhaka, Bangladesh",
    batch: 2021,
    password: "securePass1",
    fatherMotherName: "Abul Hossain & Ayesha Begum",
    gender: "Male",
    photo: "photo_url_1",
    sscRoll: 123456,
    sscReg: 654321,
    sscPassingYear: 2015,
    sscResult: 4.9,
    sscSchool: "Dhaka High School",
    sscBoard: "Dhaka",
    sscGroup: "Science",
    hscRoll: 223344,
    hscReg: 443322,
    hscPassingYear: 2017,
    hscResult: 4.8,
    hscCollege: "Dhaka College",
    hscBoard: "Dhaka",
    hscGroup: "Science",
  },
  {
    id: 2,
      name: "Mira Khan",
    email: "mira.khan@gmail.com",
    phone: "+8801745671234",
    dob: "1999-08-14",
    address: "Chittagong, Bangladesh",
    batch: 2021,
    password: "securePass2",
    fatherMotherName: "Jamal Khan & Nasima Khan",
    gender: "Female",
    photo: "photo_url_2",
    sscRoll: 223344,
    sscReg: 443322,
    sscPassingYear: 2015,
    sscResult: 4.7,
    sscSchool: "Chittagong High School",
    sscBoard: "Chittagong",
    sscGroup: "Commerce",
    hscRoll: 334455,
    hscReg: 554433,
    hscPassingYear: 2017,
    hscResult: 4.6,
    hscCollege: "Chittagong College",
    hscBoard: "Chittagong",
    hscGroup: "Commerce",
  },
  {
    id: 3,
    name: "Tanvir Ahmed",
    email: "tanvir.ahmed@gmail.com",
    phone: "+8801712345678",
    dob: "1998-11-10",
    address: "Sylhet, Bangladesh",
    batch: 2021,
    password: "securePass3",
    fatherMotherName: "Faisal Ahmed & Laila Ahmed",
    gender: "Male",
    photo: "photo_url_3",
    sscRoll: 334455,
    sscReg: 554433,
    sscPassingYear: 2015,
    sscResult: 4.9,
    sscSchool: "Sylhet High School",
    sscBoard: "Sylhet",
    sscGroup: "Science",
    hscRoll: 445566,
    hscReg: 665544,
    hscPassingYear: 2017,
    hscResult: 4.8,
    hscCollege: "Sylhet Government College",
    hscBoard: "Sylhet",
    hscGroup: "Science",
  },
  {
    id: 4,
    name: "Sara Rahman",
    email: "sara.rahman@gmail.com",
    phone: "+8801723456789",
    dob: "2000-02-10",
    address: "Rajshahi, Bangladesh",
    batch: 2021,
    password: "securePass4",
    fatherMotherName: "Anis Rahman & Farida Rahman",
    gender: "Female",
    photo: "photo_url_4",
    sscRoll: 445566,
    sscReg: 665544,
    sscPassingYear: 2016,
    sscResult: 5.0,
    sscSchool: "Rajshahi Girls High School",
    sscBoard: "Rajshahi",
    sscGroup: "Humanities",
    hscRoll: 556677,
    hscReg: 776655,
    hscPassingYear: 2018,
    hscResult: 4.7,
    hscCollege: "Rajshahi College",
    hscBoard: "Rajshahi",
    hscGroup: "Humanities",
  },
  {
    id: 5,
    name: "Riyad Chowdhury",
    email: "riyad.chowdhury@gmail.com",
    phone: "+8801719988776",
    dob: "1997-05-05",
    address: "Khulna, Bangladesh",
    batch: 2021,
    password: "securePass5",
    fatherMotherName: "Shafiq Chowdhury & Rina Chowdhury",
    gender: "Male",
    photo: "photo_url_5",
    sscRoll: 556677,
    sscReg: 776655,
    sscPassingYear: 2014,
    sscResult: 4.5,
    sscSchool: "Khulna Zilla School",
    sscBoard: "Khulna",
    sscGroup: "Science",
    hscRoll: 667788,
    hscReg: 887766,
    hscPassingYear: 2016,
    hscResult: 4.6,
    hscCollege: "Khulna College",
    hscBoard: "Khulna",
    hscGroup: "Science",
  },
  {
    id: 6,
    name: "Nadia Islam",
    email: "nadia.islam@gmail.com",
    phone: "+8801711223344",
    dob: "1999-03-20",
    address: "Barisal, Bangladesh",
    batch: 2021,
    password: "securePass6",
    fatherMotherName: "Kamal Islam & Shirin Islam",
    gender: "Female",
    photo: "photo_url_6",
    sscRoll: 667788,
    sscReg: 887766,
    sscPassingYear: 2015,
    sscResult: 5.0,
    sscSchool: "Barisal Government Girls School",
    sscBoard: "Barisal",
    sscGroup: "Science",
    hscRoll: 778899,
    hscReg: 998877,
    hscPassingYear: 2017,
    hscResult: 4.9,
    hscCollege: "Barisal Government College",
    hscBoard: "Barisal",
    hscGroup: "Science",
  },
  {
    id: 7,
    name: "Fahim Hassan",
    email: "fahim.hassan@gmail.com",
    phone: "+8801711334455",
    dob: "1998-09-11",
    address: "Rangpur, Bangladesh",
    batch: 2021,
    password: "securePass7",
    fatherMotherName: "Hasib Hassan & Rahima Hassan",
    gender: "Male",
    photo: "photo_url_7",
    sscRoll: 778899,
    sscReg: 998877,
    sscPassingYear: 2015,
    sscResult: 4.8,
    sscSchool: "Rangpur Zilla School",
    sscBoard: "Rangpur",
    sscGroup: "Commerce",
    hscRoll: 889900,
    hscReg: 110099,
    hscPassingYear: 2017,
    hscResult: 4.7,
    hscCollege: "Rangpur Government College",
    hscBoard: "Rangpur",
    hscGroup: "Commerce",
  },
  {
    id: 8,
    name: "Lina Akter",
    email: "lina.akter@gmail.com",
    phone: "+8801723456788",
    dob: "1997-12-22",
    address: "Mymensingh, Bangladesh",
    batch: 2021,
    password: "securePass8",
    fatherMotherName: "Kazi Akter & Nazma Akter",
    gender: "Female",
    photo: "photo_url_8",
    sscRoll: 889900,
    sscReg: 110099,
    sscPassingYear: 2014,
    sscResult: 4.6,
    sscSchool: "Mymensingh Girls High School",
    sscBoard: "Mymensingh",
    sscGroup: "Humanities",
    hscRoll: 990011,
    hscReg: 110099,
    hscPassingYear: 2016,
    hscResult: 4.5,
    hscCollege: "Mymensingh Government College",
    hscBoard: "Mymensingh",
    hscGroup: "Humanities",
  },
  {
    id: 9,
    name: "Samiul Islam",
    email: "samiul.islam@gmail.com",
    phone: "+8801756789123",
    dob: "1999-04-15",
    address: "Jessore, Bangladesh",
    batch: 2021,
    password: "securePass9",
    fatherMotherName: "Ismail Islam & Nurjahan Islam",
    gender: "Male",
    photo: "photo_url_9",
    sscRoll: 990011,
    sscReg: 110099,
    sscPassingYear: 2015,
    sscResult: 4.8,
    sscSchool: "Jessore High School",
    sscBoard: "Jessore",
    sscGroup: "Science",
    hscRoll: 110011,
    hscReg: 220022,
    hscPassingYear: 2017,
    hscResult: 4.7,
    hscCollege: "Jessore College",
    hscBoard: "Jessore",
    hscGroup: "Science",
  },
  {
    id: 10,
    name: "Afia Sultana",
    email: "afia.sultana@gmail.com",
    phone: "+8801756789124",
    dob: "2000-01-30",
    address: "Comilla, Bangladesh",
    batch: 2021,
    password: "securePass10",
    fatherMotherName: "Shahidul Islam & Parvin Islam",
    gender: "Female",
    photo: "photo_url_10",
    sscRoll: 220022,
    sscReg: 330033,
    sscPassingYear: 2016,
    sscResult: 4.9,
    sscSchool: "Comilla Victoria High School",
    sscBoard: "Comilla",
    sscGroup: "Science",
    hscRoll: 330033,
    hscReg: 440044,
    hscPassingYear: 2018,
    hscResult: 4.8,
    hscCollege: "Comilla College",
    hscBoard: "Comilla",
    hscGroup: "Science",
  },
];

export const teacherList = [
  {
    id: 1,
    name: "Dr. John Doe",
    designation: "Professor",
    email: "john.doe@example.com",
    phone: "123-456-7890",
    gender: "Male",
    photo: "path/to/photo1.jpg",
    degree: [
      {
        name: "BSc in Physics",
        year: "2005",
        result: "3.7",
        university: "XYZ University",
      },
      {
        name: "MSc in Physics",
        year: "2007",
        result: "3.9",
        university: "ABC University",
      },
    ],
    description:
      "Expert in Quantum Mechanics with over 15 years of teaching experience.",
    experience: [
      {
        institution_name: "XYZ University",
        designation: "Assistant Professor",
        start_date: "2010",
        end_date: "2015",
      },
      {
        institution_name: "ABC University",
        designation: "Associate Professor",
        start_date: "2015",
        end_date: "2021",
      },
    ],
    research: "Quantum Computing and Entanglement",
    publication: "Over 50 publications in international journals",
    date_of_birth: "1979-04-12",
    address: "123 University Avenue, Cityville",
  },
  {
    id: 2,
    name: "Dr. Jane Smith",
    designation: "Associate Professor",
    email: "jane.smith@example.com",
    phone: "234-567-8901",
    gender: "Female",
    photo: "path/to/photo2.jpg",
    degree: [
      {
        name: "BSc in Biology",
        year: "2003",
        result: "3.8",
        university: "ABC University",
      },
      {
        name: "PhD in Molecular Biology",
        year: "2008",
        result: "4.0",
        university: "XYZ University",
      },
    ],
    description: "Focused on molecular genetics and advanced biology.",
    experience: [
      {
        institution_name: "XYZ University",
        designation: "Lecturer",
        start_date: "2008",
        end_date: "2013",
      },
      {
        institution_name: "ABC University",
        designation: "Associate Professor",
        start_date: "2013",
        end_date: "Present",
      },
    ],
    research: "Gene Editing and Molecular Mechanisms",
    publication: "Published in Nature and Science journals.",
    date_of_birth: "1980-08-20",
    address: "456 Science Lane, Bioville",
  },
  {
    id: 3,
    name: "Dr. Alan Brown",
    designation: "Assistant Professor",
    email: "alan.brown@example.com",
    phone: "345-678-9012",
    gender: "Male",
    photo: "path/to/photo3.jpg",
    degree: [
      {
        name: "BSc in Mathematics",
        year: "2004",
        result: "3.5",
        university: "DEF University",
      },
      {
        name: "PhD in Statistics",
        year: "2009",
        result: "3.9",
        university: "GHI University",
      },
    ],
    description: "Specializes in statistical modeling and data science.",
    experience: [
      {
        institution_name: "DEF University",
        designation: "Lecturer",
        start_date: "2009",
        end_date: "2014",
      },
      {
        institution_name: "XYZ University",
        designation: "Assistant Professor",
        start_date: "2014",
        end_date: "Present",
      },
    ],
    research: "Big Data and Predictive Analytics",
    publication: "Authored several textbooks on statistics.",
    date_of_birth: "1978-12-30",
    address: "789 Math Road, StatCity",
  },
  {
    id: 4,
    name: "Dr. Emily White",
    designation: "Lecturer",
    email: "emily.white@example.com",
    phone: "456-789-0123",
    gender: "Female",
    photo: "path/to/photo4.jpg",
    degree: [
      {
        name: "BA in English",
        year: "2005",
        result: "3.7",
        university: "JKL University",
      },
      {
        name: "MA in English Literature",
        year: "2007",
        result: "3.9",
        university: "MNO University",
      },
    ],
    description:
      "Passionate about teaching English literature and linguistics.",
    experience: [
      {
        institution_name: "MNO University",
        designation: "Teaching Assistant",
        start_date: "2007",
        end_date: "2010",
      },
      {
        institution_name: "PQR University",
        designation: "Lecturer",
        start_date: "2010",
        end_date: "Present",
      },
    ],
    research: "19th Century English Literature",
    publication: "Published articles on Victorian literature.",
    date_of_birth: "1985-07-22",
    address: "101 Literature Ave, Booktown",
  },
  {
    id: 5,
    name: "Dr. Richard Green",
    designation: "Professor",
    email: "richard.green@example.com",
    phone: "567-890-1234",
    gender: "Male",
    photo: "path/to/photo5.jpg",
    degree: [
      {
        name: "BSc in Chemistry",
        year: "1999",
        result: "3.6",
        university: "ABC University",
      },
      {
        name: "PhD in Organic Chemistry",
        year: "2004",
        result: "3.9",
        university: "XYZ University",
      },
    ],
    description: "Research in organic synthesis and medicinal chemistry.",
    experience: [
      {
        institution_name: "ABC University",
        designation: "Postdoctoral Researcher",
        start_date: "2004",
        end_date: "2008",
      },
      {
        institution_name: "XYZ University",
        designation: "Professor",
        start_date: "2008",
        end_date: "Present",
      },
    ],
    research: "Synthetic Organic Chemistry",
    publication: "Co-author of 'Advanced Organic Chemistry' textbook.",
    date_of_birth: "1974-05-10",
    address: "202 Chemistry Drive, SynthCity",
  },
  {
    id: 6,
    name: "Dr. Sarah Johnson",
    designation: "Assistant Professor",
    email: "sarah.johnson@example.com",
    phone: "678-901-2345",
    gender: "Female",
    photo: "path/to/photo6.jpg",
    degree: [
      {
        name: "BA in History",
        year: "2006",
        result: "3.8",
        university: "PQR University",
      },
      {
        name: "PhD in Medieval History",
        year: "2011",
        result: "4.0",
        university: "DEF University",
      },
    ],
    description: "Focuses on medieval European history.",
    experience: [
      {
        institution_name: "DEF University",
        designation: "Research Fellow",
        start_date: "2011",
        end_date: "2015",
      },
      {
        institution_name: "XYZ University",
        designation: "Assistant Professor",
        start_date: "2015",
        end_date: "Present",
      },
    ],
    research: "Medieval European Politics",
    publication: "Published in multiple history journals.",
    date_of_birth: "1982-11-11",
    address: "303 History Lane, PastCity",
  },
  {
    id: 7,
    name: "Dr. Michael Lee",
    designation: "Lecturer",
    email: "michael.lee@example.com",
    phone: "789-012-3456",
    gender: "Male",
    photo: "path/to/photo7.jpg",
    degree: [
      {
        name: "BSc in Computer Science",
        year: "2010",
        result: "3.7",
        university: "STU University",
      },
      {
        name: "MSc in Artificial Intelligence",
        year: "2012",
        result: "3.9",
        university: "VWX University",
      },
    ],
    description: "Teaches AI and machine learning courses.",
    experience: [
      {
        institution_name: "VWX University",
        designation: "Teaching Assistant",
        start_date: "2012",
        end_date: "2015",
      },
      {
        institution_name: "XYZ University",
        designation: "Lecturer",
        start_date: "2015",
        end_date: "Present",
      },
    ],
    research: "Artificial Intelligence and Robotics",
    publication: "Published in AI research journals.",
    date_of_birth: "1988-03-05",
    address: "404 Tech Drive, Silicon Valley",
  },
  {
    id: 8,
    name: "Dr. Helen Martin",
    designation: "Professor",
    email: "helen.martin@example.com",
    phone: "890-123-4567",
    gender: "Female",
    photo: "path/to/photo8.jpg",
    degree: [
      {
        name: "BSc in Psychology",
        year: "2001",
        result: "3.8",
        university: "UVW University",
      },
      {
        name: "PhD in Clinical Psychology",
        year: "2006",
        result: "3.9",
        university: "RST University",
      },
    ],
    description: "Specializes in mental health and cognitive therapy.",
    experience: [
      {
        institution_name: "RST University",
        designation: "Postdoctoral Researcher",
        start_date: "2006",
        end_date: "2010",
      },
      {
        institution_name: "UVW University",
        designation: "Professor",
        start_date: "2010",
        end_date: "Present",
      },
    ],
    research: "Cognitive Behavioral Therapy (CBT)",
    publication: "Several studies published on mental health treatment.",
    date_of_birth: "1977-06-15",
    address: "505 Therapy Street, Mindtown",
  },
  {
    id: 9,
    name: "Dr. Joseph King",
    designation: "Associate Professor",
    email: "joseph.king@example.com",
    phone: "901-234-5678",
    gender: "Male",
    photo: "path/to/photo9.jpg",
    degree: [
      {
        name: "BSc in Engineering",
        year: "2000",
        result: "3.5",
        university: "YZA University",
      },
      {
        name: "MSc in Electrical Engineering",
        year: "2002",
        result: "3.9",
        university: "BCD University",
      },
    ],
    description: "Electrical engineer with expertise in robotics.",
    experience: [
      {
        institution_name: "BCD University",
        designation: "Lecturer",
        start_date: "2002",
        end_date: "2006",
      },
      {
        institution_name: "XYZ University",
        designation: "Associate Professor",
        start_date: "2006",
        end_date: "Present",
      },
    ],
    research: "Robotics and Automation",
    publication: "Published in leading engineering journals.",
    date_of_birth: "1975-09-25",
    address: "606 Innovation Street, Roboville",
  },
  {
    id: 10,
    name: "Dr. Lisa Turner",
    designation: "Lecturer",
    email: "lisa.turner@example.com",
    phone: "012-345-6789",
    gender: "Female",
    photo: "path/to/photo10.jpg",
    degree: [
      {
        name: "BSc in Political Science",
        year: "2004",
        result: "3.8",
        university: "EFG University",
      },
      {
        name: "MA in International Relations",
        year: "2006",
        result: "4.0",
        university: "HIJ University",
      },
    ],
    description: "Specializes in international relations and political theory.",
    experience: [
      {
        institution_name: "EFG University",
        designation: "Teaching Assistant",
        start_date: "2006",
        end_date: "2009",
      },
      {
        institution_name: "HIJ University",
        designation: "Lecturer",
        start_date: "2009",
        end_date: "Present",
      },
    ],
    research: "Global Politics and International Diplomacy",
    publication: "Published articles in political science journals.",
    date_of_birth: "1980-02-10",
    address: "707 Politics Road, Governcity",
  },
  {
    id: 11,
    name: "Dr. David Harris",
    designation: "Assistant Professor",
    email: "david.harris@example.com",
    phone: "123-456-7891",
    gender: "Male",
    photo: "path/to/photo11.jpg",
    degree: [
      {
        name: "BSc in Sociology",
        year: "2002",
        result: "3.5",
        university: "LMN University",
      },
      {
        name: "PhD in Social Psychology",
        year: "2007",
        result: "3.9",
        university: "OPQ University",
      },
    ],
    description: "Expert in social psychology and behavioral studies.",
    experience: [
      {
        institution_name: "LMN University",
        designation: "Lecturer",
        start_date: "2007",
        end_date: "2012",
      },
      {
        institution_name: "OPQ University",
        designation: "Assistant Professor",
        start_date: "2012",
        end_date: "Present",
      },
    ],
    research: "Behavioral Economics and Social Influence",
    publication: "Published several papers in top journals.",
    date_of_birth: "1981-11-01",
    address: "808 Social St, Psychoville",
  },
  {
    id: 12,
    name: "Dr. Natalie Roberts",
    designation: "Professor",
    email: "natalie.roberts@example.com",
    phone: "234-567-8902",
    gender: "Female",
    photo: "path/to/photo12.jpg",
    degree: [
      {
        name: "BSc in Geology",
        year: "1998",
        result: "3.7",
        university: "RST University",
      },
      {
        name: "PhD in Environmental Science",
        year: "2003",
        result: "3.9",
        university: "UVW University",
      },
    ],
    description: "Researches environmental impact and climate change.",
    experience: [
      {
        institution_name: "UVW University",
        designation: "Postdoctoral Fellow",
        start_date: "2003",
        end_date: "2007",
      },
      {
        institution_name: "XYZ University",
        designation: "Professor",
        start_date: "2007",
        end_date: "Present",
      },
    ],
    research: "Environmental Sustainability and Climate Modeling",
    publication: "Over 40 publications in environmental journals.",
    date_of_birth: "1976-10-22",
    address: "909 Earth Lane, EcoCity",
  },
];

export const batchList = [
  {
    id: 1,
    batchName: "Batch A",
    courseCode: "CSE101",
    startDate: "2023-01-15",
    endDate: "2024-01-15",
    totalStudents: 50,
  },
  {
    id: 2,
    batchName: "Batch B",
    courseCode: "CSE102",
    startDate: "2023-02-01",
    endDate: "2024-02-01",
    totalStudents: 45,
  },
  {
    id: 3,
    batchName: "Batch C",
    courseCode: "CSE103",
    startDate: "2023-03-01",
    endDate: "2024-03-01",
    totalStudents: 60,
  },
  {
    id: 4,
    batchName: "Batch D",
    courseCode: "CSE104",
    startDate: "2023-04-10",
    endDate: "2024-04-10",
    totalStudents: 40,
  },
  {
    id: 5,
    batchName: "Batch E",
    courseCode: "CSE105",
    startDate: "2023-05-15",
    endDate: "2024-05-15",
    totalStudents: 55,
  },
];
